version: '3.0'

services:

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: a123456
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql

  pg:
    image: postgres
    container_name: pg
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: a123456
    volumes:
      - ./data/pg:/var/lib/postgresql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
