version: '3.5'

networks:
  gonet:
    driver: bridge

services:

  db:
    image: mysql
    container_name: mysql
    restart: always
    ports:
    - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Wm123456
    volumes:
    - ./data/mysql:/var/lib/mysql
    networks:
      - gonet

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
    - 8080:8080
    networks:
      - gonet
